### ISSUE TITLE
Use correct fonts

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/og-image-generator#11]
The generated og images do not use the fonts from `vocabulary`: [Source Sans Pro and Roboto Condensed](https://cc-vocabulary.netlify.app/?path=/docs/tokens-typography--heading-title). They should be added and there should be a dropdown to choose which one is in use.

One difficulty here—the Puppeteer instance that generates the images doesn't have network access, so the woff2 files for the fonts will need to be added locally, encoded as base64, and inlined in the css. 

You can see how to do this _here_: https://github.com/vercel/og-image/blob/8026662bccaa750af4783a00e87614d1676b3b2e/api/_lib/template.ts#L10

**Comment by rajat2502** [comment]
Hey @zackkrida, I would like to work on this one.

**Comment by zackkrida** [comment]
@rajat2502 go for it!
