### ISSUE TITLE
Encode query parameters containing urls for facebook and other social media platforms.

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/og-image-generator#18]
If facebook encounters an open graph image url which has a query parameter that _also_ contains a url, it fails. Here's a fake example:

`https://myimageurl.com?query=https://another.url`

https://github.com/creativecommons/og-image-generator/blob/ba20ca7b1bf15d4e94ca8202eacf01360ccbd220/api/_lib/parser.ts#L8

This means that our open graph images which contain multiple images do not work. There's a fix and some relevant discussion that can be found here:

https://github.com/vercel/og-image/issues/131

**Comment by shubhanshu02** [comment]
Hi @zackkrida, I want to try solving this issue. Can you please assign it to me?

**Comment by CapriciousRebel** [comment]
Hello, Is this issue still open? I would like to work on this one.
