### ISSUE TITLE
Fix dark mode

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/og-image-generator#2]
For dark mode to work we need to either create inverted/white versions of our svgs, _or_ see if we can invert the black svgs to white with css (I can't remember if css filters apply to linked svgs).

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by rajat2502** [comment]
Hey @zackkrida, I did a bit of search on this, if we could modify a linked SVG using CSS/js. According to what I read we can't modify the SVG as such, we will have to use their code to modify them.
[This](https://stackoverflow.com/questions/22252472/how-to-change-the-color-of-an-svg-element#:~:text=19%20Answers&text=You%20can't%20change%20the,or%20using%20inline.) StackOverflow question surrounds around the same.

**Comment by rajat2502** [comment]
[This](https://stackoverflow.com/a/53336754/10812309) answer tells a different story, maybe we can try this out once. Let me know if I should go ahead with this.

**Comment by zackkrida** [comment]
@rajat2502 Wow, that is a very clever hack you found in the second answer! This _does_ indeed work to make the svgs white:

`
filter: invert(100%) sepia(0%) saturate(0%) hue-rotate(12deg) brightness(103%) contrast(103%);
`

Go ahead and implement this; great find.

**Comment by rajat2502** [comment]
Sure @zackkrida, I will go ahead and implement this!

**Comment by rajat2502** [comment]
![image](https://user-images.githubusercontent.com/42200276/95218852-5b5a2500-0812-11eb-8c2c-f9b63f9d3bff.png)
Getting this error while running `vercel dev`,  I think I need to modify vercel.json. Can you please help me out.
