### ISSUE TITLE
Modify height & width of SVGs used

### ISSUE THREAD

**Issue by rajat2502** [creativecommons/og-image-generator#5]
## Problem

The width & height of the images/logos should be allowed to modify.

## Description

A feature to modify the width and height of the images that are used in the og-image. This will help in fixing the overflow problem of the images.
![image](https://user-images.githubusercontent.com/42200276/95434182-95403e00-096e-11eb-9627-a9c145e8a180.png)

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by rajat2502** [comment]
I think this one is already implemented. I will close this one.

**Comment by zackkrida** [comment]
@rajat2502 One thing that would be good is forcing a `max-width: 100%` on the logos, so they can't overlap like in this screenshot.

**Comment by rajat2502** [comment]
Yeah, that would fix the issue. I will make a PR for the same.
